// Italienischer Katalog.
//
// ⚠️ IN ARBEIT — siehe en.ts. Was noch nicht übersetzt ist, kommt über `...de`
// herein und ist damit Deutsch. Sichtbare Zwischenstufe, kein Rückfall.
//
// Ton: das deutsche Sie wird zum italienischen „Lei“ (Verbform in der dritten
// Person Einzahl). Das ist in der Geschäftskommunikation die richtige Anrede
// und passt zur bestehenden deutschen Fassung; ein Wechsel zum „tu“ wäre eine
// inhaltliche Änderung und nicht eine Übersetzung.

import { de } from './de'
import type { Labels } from './index'

export const it: Labels = {
  ...de,

  catalog: {
    heading: 'Corsi e moduli',
    intro: 'Scelga un corso e un modulo per iniziare.',
    empty: 'Al momento non è disponibile alcun corso.',
    loadError: 'Non è stato possibile caricare i corsi.',
    inProgress: 'In corso',
    open: 'Apri',
    backToCatalog: '← Tutti i corsi',
    onlyPublished: 'Solo pubblicati',
    unpublishedTag: 'Non pubblicato',
    priceTitle: 'Prezzo di listino. Agli ordini si aggiunge l’IVA svizzera dell’8,1 %.',
  },

  dashboard: {
    completedCourses: 'Corsi completati',
    ofCourses: (done: number, total: number): string => `${done} di ${total} corsi`,
    certificates: 'Attestati',
    inProgressHeading: 'In corso',
    completedTag: 'Completato',
    noStarted: 'Nessun corso ancora iniziato — ne scelga uno qui sotto per cominciare.',
  },

  seat: {
    title: 'Nessun accesso a questo corso',
    noOrder:
      'Per questo corso non risulta alcun ordine della Sua organizzazione. Si rivolga alla Sua amministrazione.',
    noSeats:
      'Per questo corso tutti i posti sono occupati. Si rivolga alla Sua amministrazione.',
    generic: 'Non è stato possibile salvare i Suoi progressi.',
    close: 'Chiudi',
  },

  auth: {
    heading: 'Accesso all’area di formazione',
    intro: 'L’area di formazione è protetta. Acceda con il Suo indirizzo e-mail.',
    emailLabel: 'Indirizzo e-mail',
    emailPlaceholder: 'nome.cognome@hslu.ch',
    requestCode: 'Richiedi il codice',
    sending: 'Invio del codice…',
    codeHeading: 'Inserisca il codice',
    codeSentTo: (email: string): string =>
      `Abbiamo inviato un codice di sei cifre a ${email}. È valido per 10 minuti.`,
    codeLabel: 'Codice di accesso',
    codePlaceholder: '123456',
    verify: 'Accedi',
    verifying: 'Verifica in corso…',
    back: 'Usa un altro indirizzo e-mail',
    resend: 'Invia un nuovo codice',
    checking: 'Verifica dell’accesso…',
    logout: 'Esci',
    genericRequestError: 'Non è stato possibile inviare il codice. Riprovi.',
    wrongCode: 'Codice errato. Riprovi.',
    wrongCodeRemaining: (n: number): string =>
      n === 1 ? 'Codice errato. Resta 1 tentativo.' : `Codice errato. Restano ${n} tentativi.`,
    expiredCode: 'Il codice non è valido o è scaduto. Ne richieda uno nuovo.',
    lockedCode: 'Troppi tentativi. Richieda un nuovo codice.',
    noUser: 'Per questo indirizzo non esiste alcun accesso.',
    invalidEmail: 'Inserisca un indirizzo e-mail valido.',
  },
  appTitle: 'Formazione',
  loading: 'Caricamento…',
  noModules: 'Nessun modulo disponibile.',
  moduleSelectLabel: 'Scelga il modulo',
  resetProgress: 'Azzera i progressi',
  resetConfirm: 'Azzerare davvero i progressi? Risposte e annotazioni andranno perse.',
  progressOf: (done: number, total: number): string => `${done} / ${total} sezioni`,
  objectives: 'Obiettivi',
  prev: 'Indietro',
  next: 'Avanti',
  submit: 'Verifica la risposta',
  tryAgain: 'Riprova',
  correct: 'Corretto',
  incorrect: 'Errato',
  savedHint: 'salvato',
  validationError: 'Il JSON del modulo non è valido.',
  loadError: 'Non è stato possibile caricare il modulo.',
  missingResource: (id: string): string => `Risorsa mancante: ${id}`,
  missingAlt: 'Testo alternativo mancante',

  viewAs: {
    open: 'Vista partecipante',
    title: 'Vista partecipante',
    subtitle: 'Consulti i progressi di una persona partecipante.',
    ownView: 'La mia vista',
    noParticipants: 'In questo corso nessuno ha ancora fatto progressi.',
    banner: (name: string): string => `Vista partecipante: ${name}`,
    readOnly: 'sola lettura',
    exit: 'Torna alla mia vista',
    loadError: 'Non è stato possibile caricare i partecipanti.',
    close: 'Chiudi',
  },

  saveError: {
    title: 'Progressi non salvati',
    body:
      'Non è stato possibile salvare questo elemento sul server. Non dipende da ciò che ha inserito — può proseguire, ma per ora questo elemento non conta come completato. La preghiamo di segnalarlo alla direzione del corso.',
    detail: (artifactId: string, code: string): string => `Elemento ${artifactId} · ${code}`,
    dismiss: 'Nascondi',
  },

  llm: {
    title: 'Provi un prompt',
    model: 'Modello',
    unavailable: 'non disponibile',
    promptLabel: 'Prompt',
    promptPlaceholder: 'Scriva qui il Suo prompt …',
    send: 'Invia',
    sending: 'Invio in corso …',
    response: 'Risposta',
    refused: 'Il modello ha rifiutato la richiesta.',
    modelsError: 'Non è stato possibile caricare i modelli.',
    tokens: (input: number, output: number): string => `${input} → ${output} token`,
  },

  routes: {
    notFoundTitle: 'Questo indirizzo non porta da nessuna parte',
    notFoundBody:
      'L’indirizzo punta a qualcosa che non esiste (più) — oppure i segmenti non corrispondono. Verifichi il collegamento.',
    toCatalog: '← Alla panoramica dei corsi',
    resolving: 'Risoluzione in corso …',
    supersededTitle: 'Versione superata',
    supersededBody: (v: number): string =>
      `Sta consultando la versione ${v}. Di questo corso esiste una versione attiva più recente.`,
    toActive: 'Alla versione attuale',
    courseModules: 'Moduli',
    noModules: 'Questo corso non contiene ancora moduli.',
    unpublishedTag: 'Non pubblicato',
    adminOnlyHint:
      'Per i partecipanti questo indirizzo è un 404 — i corsi non pubblicati non sono visibili.',
  },

  media: {
    download: 'Scarica',
    dropHint: 'Trascini qui un file o faccia clic — PDF, Excel, video, immagine',
    uploading: 'Caricamento …',
    uploadError: 'Caricamento non riuscito.',
    needCourse: 'I caricamenti richiedono il contesto di un corso — questo modulo è aperto senza.',
    remove: 'Rimuovi il file',
    orUrl: 'oppure incolli un indirizzo',
  },

  mcp: {
    url: 'URL del server MCP',
    urlPlaceholder: 'https://…/mcp',
    connect: 'Connetti',
    connecting: 'Connessione …',
    connected: 'Connesso',
    disconnect: 'Disconnetti',
    tools: 'Strumenti',
    noTools: 'Il server non segnala alcuno strumento.',
    selectToolHint: 'Scelga a sinistra uno strumento per eseguirlo.',
    parameters: 'Parametri',
    noParams: 'Questo strumento non ha parametri.',
    run: 'Esegui',
    running: 'Esecuzione …',
    result: 'Risultato',
    error: 'Errore',
    required: 'obbligatorio',
    stepUrl: 'Server connesso',
    stepTool: 'Strumento eseguito',
    done: 'Completato',
    authRequired: 'Questo server richiede l’accesso',
    authHint:
      'Si aprirà la finestra di accesso del fornitore. L’accesso passa poi dal nostro server; il Suo token resta lì e non viene conservato nel browser.',
    signIn: 'Accedi',
    signingIn: 'Accesso in corso …',
    authFailed: 'L’accesso è stato annullato o non è riuscito.',
    popupBlocked: 'La finestra di accesso è stata bloccata. Consenta i pop-up per questo sito.',
    viaProxy: 'tramite il nostro server',
    authenticated: 'connesso',
    signOut: 'Esci',
  },

  ontologyBlock: {
    classes: 'Classi',
    relationships: 'Relazioni',
    node: 'Nodo',
    edge: 'Arco',
    erpCore: 'Nucleo ERP',
    extensions: 'Estensioni',
    erpTag: 'ERP',
    extensionTag: 'previsto',
    attributes: 'Attributi',
    relOut: 'Relazioni (in uscita)',
    relIn: 'Relazioni (in entrata)',
  },

  dataQuery: {
    run: 'Esegui',
    running: 'In corso …',
    hint: '⌘/Ctrl + Invio',
    syntaxToggle: 'Sintassi supportata',
    syntaxBody:
      'Una tabella (una classe dell’ontologia), nessun JOIN. WHERE con AND/OR e = != < <= > >= LIKE. Sola lettura.',
    rowCount: (n: number, coll: string): string => `${n} rig${n === 1 ? 'a' : 'he'} da ${coll}`,
    noRows: 'Nessuna riga — modifichi le condizioni.',
  },

  docConvert: {
    drop: 'Trascini qui un file o faccia clic',
    formats: 'PDF, PPTX, DOCX, immagini → Markdown · Excel → Markdown, vista celle + analisi',
    converting: 'Conversione …',
    raw: 'Testo grezzo',
    rendered: 'Visualizzato',
    copyAll: 'Copia tutto',
    copied: 'Copiato ✓',
    tab: { markdown: 'Markdown', cells: 'Celle', analysis: 'Analisi' },
    cellsNotApplicable: 'Vista celle non applicabile — questo file non ha struttura tabellare.',
    cellsTruncated: 'Output troncato — il file supera il limite di visualizzazione.',
    formulaModeLabel: (m: string): string =>
      m === 'formula' ? 'formule visibili' : m === 'error' ? 'valori di errore visibili' : 'solo valori',
  },

  objectGraph: {
    seed: 'Inizio:',
    hint: 'Faccia clic su un nodo per caricarne i vicini',
    nodeCount: (n: number): string => `${n} nodi`,
    cypherRun: 'Interroga',
    cypherClear: 'Azzera',
    // Unveraendert: die Knotenbezeichner sind Daten aus der Ontologie, keine
    // Beschriftung. Uebersetzt liefe die Abfrage ins Leere.
    cypherPlaceholder: 'MATCH (a:Liegenschaft)<-[:liegt_in]-(u:Einheit) RETURN a, u',
    matchCount: (n: number): string => `${n} risultati evidenziati`,
  },

  chat: {
    title: 'Assistente del corso',
    subtitle: 'Domande sul materiale del corso',
    open: 'Apri l’assistente',
    close: 'Chiudi',
    welcome: 'Buongiorno! Rispondo a domande sul materiale dei corsi AI@RE. Che cosa desidera sapere?',
    suggestionsTitle: 'Domande frequenti',
    suggestions: [
      'Che cos’è l’AI readiness?',
      'Mi spieghi il Transformation Circle',
      'In che modo l’IA aiuta nella valutazione?',
    ],
    placeholder: 'Scriva la Sua domanda …',
    send: 'Invia',
    sources: 'Fonti',
    disclaimer: 'Le risposte possono contenere errori. Verifichi le informazioni importanti.',
    error: 'Qualcosa è andato storto. Riprovi.',
  },
  embeddingCompare: {
    title: 'Confronta gli embedding',
    listHeading: 'Frammenti di testo',
    addPlaceholder: 'Incolli un frammento, lo scriva, oppure trascini qui un file di testo …',
    add: 'Aggiungi',
    addChunked: (n: number): string => `Suddividi in ${n} frammenti`,
    dropHint: 'Trascini testo o un file di testo',
    fileTooBig: 'Il file è troppo grande — al massimo 2 MB di testo.',
    chunkSize: 'Dimensione del frammento',
    chunkOverlap: 'Sovrapposizione',
    chars: 'caratteri',
    chunkHint:
      'Il testo lungo viene suddiviso al momento dell’inserimento — esattamente come in una '
      + 'pipeline RAG, che non vede mai un documento ma solo i suoi frammenti. Il taglio avviene '
      + 'di preferenza ai capoversi, altrimenti ai confini di frase o di parola. La '
      + 'sovrapposizione ripete la fine del frammento precedente, così un’affermazione non va '
      + 'persa sulla giuntura. Come regola pratica, quattro caratteri equivalgono a circa un token.',
    splitInto: (n: number): string =>
      `Il testo appena aggiunto è stato suddiviso in ${n} frammenti.`,
    chunkBadge: (i: number, total: number): string => `Frammento ${i}/${total}`,
    modePlane: 'Piano',
    modeRetrieve: 'Recupero',
    modePlaneHint: 'Tutti i frammenti fra loro — utile per pochi testi.',
    modeRetrieveHint: 'Una domanda contro tutti i frammenti — così cerca il RAG.',
    tooManyForPlane: (n: number, edges: number): string =>
      `${n} punti producono ${edges} linee di collegamento — ormai illeggibile.`,
    switchToRetrieve: 'Passa al recupero',
    queryLabel: 'Domanda',
    queryPlaceholder: 'Che cosa si deve trovare? Per esempio: chi sostiene i costi di manutenzione?',
    retrieveAction: 'Recupera',
    retrieveAgain: 'Recupera di nuovo',
    topK: 'Frammenti nel contesto',
    chunks: 'frammenti',
    needQuery: 'Formuli prima una domanda.',
    needOne: 'Selezioni almeno un frammento.',
    retrievalDirty: 'La domanda o la selezione è cambiata — recuperi di nuovo.',
    cutoff: 'Da qui in giù: fuori dal contesto',
    contextSummary: (k: number, chars: number, total: number): string =>
      `${k} frammenti su ${total} sono andati al modello come contesto — ${chars} caratteri in tutto.`,
    retrievalNote:
      'Il modello vede solo ciò che sta sopra la linea. Tutto ciò che sta sotto continua a '
      + 'esistere nella raccolta e comunque non compare nella risposta — anche quando è corretto. '
      + 'È proprio qui che nascono le lacune che poi si attribuiscono al modello.',
    colMedium: 'Supporto',
    colDescription: 'Descrizione',
    remove: 'Rimuovi',
    selectAll: 'Seleziona tutto',
    selectOne: 'Seleziona la voce',
    removeSelected: 'Rimuovi i selezionati',
    removeSelectedTitle: (n: number): string => `Rimuovi ${n} voci selezionate`,
    removeSelectedNone: 'Selezioni prima delle voci',
    removeManyConfirm: (n: number): string =>
      `Rimuovere ${n} voci dalla mediateca? I file restano archiviati.`,
    empty: 'Nessun frammento. Ne aggiunga due o più per confrontarli.',
    selectHint: 'I frammenti selezionati sono mostrati sotto come punti.',
    compute: 'Confronta',
    computing: 'Calcolo dei vettori …',
    recompute: 'Ricalcola',
    needTwo: 'Selezioni almeno due frammenti.',
    dirty: 'La selezione è cambiata — ricalcoli.',
    modelLine: (model: string, dims: number): string => `${model} · ${dims} dimensioni`,
    distanceHint: 'L’etichetta indica la distanza angolare: 0 = stessa direzione, 1 = opposta.',
    exact:
      'Questa rappresentazione è esatta — tre punti si dispongono sempre su un piano senza distorsione.',
    projected: (pct: string): string =>
      `Proiezione: da quattro testi in poi le distanze non entrano più in un piano senza distorsione. Distorsione ${pct}.`,
    projectedNote:
      'I numeri sulle linee sono le distanze reali; le lunghezze disegnate sono solo la migliore approssimazione possibile.',
    error: 'Non è stato possibile calcolare i vettori.',
    notConfigured: 'Per questo elemento non è ancora configurato alcun servizio di embedding.',
  },

  agentLoop: {
    blockLabel: 'Il ciclo dell’agente',
    scenarios: {
      scn_offerten_v1: {
        label: 'Analisi dell’offerta',
        note: 'L’agente riceve una documentazione di vendita e strumenti di ubicazione — ma non il documento nel proprio contesto.',
      },
      scn_rollen_cfo_v1: {
        label: 'Skill di ruolo: CFO',
        note: 'L’agente dispone di una skill di ruolo come file e di un grafo della conoscenza con provenienza. I primi cicli leggono istruzioni anziché dati.',
      },
    },
    loading: 'Caricamento …',
    retry: 'Riprova',
    loadError: 'Non è stato possibile caricare.',

    taskLabel: 'Domanda per l’agente',
    taskPlaceholder: 'p. es. Il prezzo richiesto è plausibile?',
    documentLabel: 'Documentazione di vendita',
    documentHint:
      'Markdown. L’agente non riceve questo testo nel proprio contesto — recupera le sezioni con gli strumenti. Può inserire una propria offerta; i dati di ubicazione conoscono però solo gli indirizzi archiviati.',
    modelLabel: 'Modello',
    start: 'Crea l’esecuzione',
    starting: 'Creazione …',
    startFailed: 'Non è stato possibile avviare l’esecuzione.',
    whatAgentGets: (n: number): string => `Che cosa riceve l’agente (${n} strumenti)`,
    systemPrompt: 'Prompt di sistema',
    tools: 'Strumenti',

    newRun: 'Nuova esecuzione',
    kModel: 'Modello',
    kTurns: 'Cicli',
    kTurnsOf: (n: number, max: number): string => `${n} di ${max}`,
    kConversation: 'Conversazione',
    kMessages: (n: number): string => `${n} messaggi`,
    kTokens: 'Token',
    kTokensValue: (inTok: string, outTok: string): string => `${inTok} in · ${outTok} out`,
    kResent: 'di cui ripetuti',

    tabFlow: 'Svolgimento',
    tabLog: (n: number): string => `Protocollo (${n})`,

    cycleModel: 'Interroga il modello',
    cycleBranch: 'Strumento richiamato?',
    cycleTool: 'Esegui lo strumento',
    cycleAppend: 'Aggiungi il risultato',
    atStart: 'L’esecuzione è creata. Al modello non è ancora stato inviato nulla.',
    atModel: 'Il modello sta ragionando — l’intera conversazione precedente parte con esso.',
    atAppend:
      'I risultati degli strumenti fanno ora parte della conversazione. Il ciclo successivo invia di nuovo tutto.',
    atStopped: 'Il limite è raggiunto. L’agente è stato fermato — non aveva finito.',
    atDone: 'Il modello ha risposto senza richiamare alcuno strumento. Il ciclo termina qui.',

    noTurnYet: 'Nessun ciclo finora.',
    turnN: (n: number): string => `Ciclo ${n}`,
    seconds: (s: string): string => `${s} s`,
    conversationAtCall: 'Conversazione a questa chiamata:',
    reasoning: 'Ragionamento',
    answerField: 'Risposta',
    textBesideCall: 'Testo accanto alla chiamata',
    toolInput: 'Ingresso',
    toolOutput: 'Uscita',
    unknownTool:
      'Questo strumento non esiste. L’agente riceve un errore e può fare meglio al ciclo successivo.',

    outToolUse: 'strumento richiamato → prosegue',
    outFinal: 'nessuno strumento → fine',
    outMaxTurns: 'limite → fermato',
    outError: 'Errore',

    stepFirst: 'Avvia il primo ciclo',
    stepNext: 'Ciclo successivo',
    stepRunning: 'Ciclo in corso …',
    stepHint: 'Un clic = una chiamata al modello. Parte tutta la conversazione.',
    stepFailed: 'Il ciclo non è riuscito.',
    result: 'Risultato',
    stoppedNote: (max: number): string =>
      `Il limite di ${max} cicli è raggiunto. L’agente è stato fermato — non è un risultato, è un’interruzione.`,

    noTurnRecorded: 'Nessun ciclo registrato finora.',
    call: 'Chiamata',
    showInFlow: 'Mostra nello svolgimento',
    turnLoadError: 'Non è stato possibile caricare il ciclo.',
    logIntro: (index: number, messages: number, tools: number): string =>
      `Il contenuto completo della chiamata ${index}: ${messages} ${messages === 1 ? 'messaggio' : 'messaggi'} più il prompt di sistema e ${tools} dichiarazioni di strumenti. Alla chiamata successiva riparte tutto — questa è l’intera memoria dell’agente.`,
  },
  register: {
    title: 'Registrati',
    titleDone: 'Registrazione completata',
    close: 'Chiudi',
    firstName: 'Nome',
    lastName: 'Cognome',
    email: 'Indirizzo e-mail',
    emailPlaceholder: 'nome.cognome@azienda.ch',
    company: 'Azienda',
    street: 'Via',
    streetNumber: 'Numero',
    postalCode: 'NPA',
    city: 'Località',
    country: 'Paese',
    countries: { CH: 'Svizzera', DE: 'Germania', AT: 'Austria' },
    submit: 'Registrati',
    submitting: 'Invio in corso …',
    unreachable: 'Il server non è raggiungibile. Riprovi più tardi.',
    doneAccount: (customer: string): string => `Il Suo accesso per ${customer} è stato creato.`,
    doneCustomerCreated:
      'La Sua organizzazione non era ancora registrata — da ora la amministra Lei: ne vede gli utenti e può ordinare corsi per essa.',
    doneCustomerExisting: 'La Sua organizzazione è già registrata. È stato aggiunto come utente.',
    doneInvited:
      'Un’e-mail sulla procedura di accesso è in arrivo. Non esiste una password — inserisce il Suo indirizzo nella pagina di accesso e riceve un codice.',
    doneNotInvited:
      'Non è stato possibile recapitare l’e-mail di benvenuto. Può comunque accedere: inserisca l’indirizzo e richieda un codice.',
    toLogin: 'Accedi ora',
    haveAccount: 'Ho già un accesso',
    toSignIn: 'Vai all’accesso',
  },

  profile: {
    title: 'Il mio profilo',
    close: 'Chiudi',
    firstName: 'Nome',
    lastName: 'Cognome',
    email: 'E-mail',
    roles: 'Ruoli',
    save: 'Salva',
    saving: 'Salvataggio …',
    saved: 'Salvato.',
    unreachable: 'Il server non è raggiungibile.',
  },

  agentTrace: {
    blockLabel: 'L’agente al lavoro',
    loadingWorkspace: 'Caricamento dell’area di lavoro …',
    unreachable: 'L’area di lavoro non è raggiungibile.',
    failed: 'Non ha funzionato.',
    start: 'Avvia un’esecuzione',
    startAnother: 'Attivane un’altra',
    queuedHint:
      'Un’esecuzione è già in corso. Il Suo avvio è in coda — parte appena la prima è terminata.',
    noRun: 'Nessuna esecuzione. Scelga un agente e lo avvii.',
    killSwitch: 'Arresto d’emergenza',
    tabFiles: 'Cartelle e posta',
    tabKnows: 'Che cosa so adesso',
    tabTools: 'Strumenti disponibili',
    tabWhence: 'Da dove proviene?',
    intents: 'Intenzioni',
    noIntents: 'Ancora nulla che l’agente farebbe.',
    readThisRun: 'Letto in questa esecuzione',
    task: 'Incarico',
    instruction: 'Istruzione all’agente',
    edit: 'Modifica',
    loadScenario: 'Carica lo scenario',
    deleteWorkspace: 'Elimina l’area di lavoro',
    deleteConfirm: 'Eliminare tutti i contenuti e l’intera cronologia di questa area di lavoro?',
    technical: 'vista tecnica',
    technicalOff: 'vista tecnica disattivata',
    unverifiable: ' (passaggio non verificabile)',
    wouldDo: '(farebbe)',
    sees: '(vede)',
    run: 'Esecuzione',
    completed: 'completata',
    runningState: 'in corso',
    nothingYet: 'ancora nulla',
  },

  agentForm: {
    titleNew: 'Nuovo agente',
    titleEdit: 'Modifica agente',
    close: 'Chiudi',
    name: 'Nome',
    namePlaceholder: 'Revisore di offerte',
    model: 'Modello',
    description: 'Descrizione',
    descriptionPlaceholder: 'Esamina le offerte in entrata e propone una raccomandazione.',
    instruction: 'Istruzione',
    instructionPlaceholder:
      'Che cosa deve fare l’agente? Lo scriva come lo direbbe a un nuovo collaboratore temporaneo.',
    trigger: 'Attivazione',
    triggerFile: 'Nuovo file',
    triggerMessage: 'Nuovo messaggio',
    triggerTimer: 'A tempo',
    folderPlaceholder: 'Cartella',
    subjectPlaceholder: 'L’oggetto contiene …',
    minutes: 'minuti',
    toolsRead: 'Vede (viene eseguito)',
    toolsRecord: 'Farebbe (solo registrato)',
    maxSteps: 'Passi max.',
    enabled: 'attivo',
    save: 'Salva',
    deleteAgent: 'Elimina l’agente',
  },

  intentCard: {
    approve: 'Approva',
    reject: 'Rifiuta',
    sendRejection: 'Invia il rifiuto',
    beforeAfter: 'Prima / dopo',
  },

  orchestration: {
    loadingToolbox: 'Caricamento degli strumenti …',
    guidancePlaceholder:
      'Una regola per riga, p. es.\nVerifichi il tasso di riferimento prima di redigere una comunicazione.',
    resetConfirm:
      'Ripristinare il set iniziale di strumenti? I Suoi strumenti personali andranno persi.',
    requestPlaceholder: 'Che cosa va fatto? Lo formuli come lo direbbe a una persona.',
    needTool: 'Crei prima uno strumento.',
    promptShown: 'Che cosa è andato al modello',
    promptWould: 'Che cosa andrebbe al modello',
    noDescription: 'nessuna descrizione',
    removeTool: 'Rimuovi lo strumento',
    toolNamePlaceholder: 'cerca_contratto',
    toolDescription: 'Descrizione',
    toolDescriptionPlaceholder:
      'Che cosa fa questo strumento? Una frase — il modello ha solo questa.',
    parameters: 'Parametri',
    noParameters: 'Nessun parametro.',
    paramNamePlaceholder: 'data_riferimento',
    paramDescriptionPlaceholder: 'Che cosa rappresenta questo parametro?',
    fromRequest: 'dalla richiesta',
    ruleKept: 'rispettata',
    ruleViolated: 'non rispettata',
    ruleNotApplicable: 'non applicabile — lo strumento non compare nel piano',
    ruleUnchecked: 'non verificabile — solo l’affermazione del modello',
    wavesHint: ' — i passi dello stesso livello potrebbero essere eseguiti in parallelo.',
    undeclaredParam: 'Questo parametro non è dichiarato nello strumento.',
    requestLabel: 'Richiesta',
    guidanceLabel: 'Regole',
    toolsLabel: 'Strumenti',
    toolName: 'Nome',
    previewPrompt: 'Visualizza il prompt in anteprima (senza chiamare il modello)',
    assumptions: 'Ipotesi',
    rejectedInvented: 'Scartati: strumenti inventati',
    gaps: 'Ciò che gli strumenti non coprono',
  },
  site: {
    tagline: 'Intelligenza artificiale nel settore immobiliare',
    navHome: 'Home',
    navStatistics: 'Statistiche',
    navMarketData: 'Dati di mercato',
    navTraining: 'Formazione',
    navCoding: 'Codifica',
    navAdmin: 'Amministrazione',
    navContact: 'Contatto',
    signOut: 'Esci',
    register: 'Registrati',
    signIn: 'Accedi',
    myProfile: 'Il mio profilo',
    close: 'Chiudi',
    navigation: 'Navigazione',
    imprint: 'Note legali',
    privacy: 'Privacy',
    legalGermanOnly: 'Queste informazioni sono disponibili solo in tedesco.',
  },

  home: {
    reviewTitle: 'Retrospettiva: AI@RE 2026',
    conferenceReview:
      'La conferenza AI@RE si è svolta. Oltre 160 partecipanti. Keynote stimolanti. Deep dive avvincenti. Sessioni di break-out intense. E vincitori dell’AI@RE Award di grande valore. Grazie a tutti e soprattutto ai nostri sponsor.',
    nextConference: 'Dopo la conferenza è prima della conferenza: AI@RE, Rotkreuz, 7.6.2027',
    partnersWere: 'I nostri partner sono stati',
    startReadiness: 'Avvia il Readiness Check',
    startTransformation: 'Avvia il Transformation Check',
    viewStatistics: 'Consulta le statistiche',
    leadChange:
      'Il settore immobiliare cambia più in fretta di quanto molte aziende riescano a reagire.',
    leadBody:
      'L’IA automatizza i processi, trasforma i ruoli, sposta la creazione di valore. Molte aziende portano avanti la digitalizzazione senza sapere se le loro basi reggono.',
    consequence: 'La conseguenza:',
    consequence1: 'Progetti che falliscono — non a causa dell’IA, ma per mancanza di basi',
    consequence2: 'Team sopraffatti',
    consequence3: 'Strategie che non fanno presa',
    checkIs: 'Il Readiness Check è la Sua analisi di posizionamento in sette minuti.',
    checkShows: 'In modo neutrale, indipendente e basato sull’evidenza, Le mostra:',
    shows1: 'Quanto i Suoi dati sono pronti per l’IA',
    shows2: 'Dove la Sua organizzazione è bloccata — e dove è forte',
    shows3: 'Quali competenze mancano',
    shows4: 'Quanto è realmente ampio il Suo potenziale di attuazione',
    shows5: 'Che cosa può fare subito per essere in grado di agire',
    dimensionsTitle: 'Che cosa misura esattamente il Readiness Check?',
    dimensionsLead:
      'Analizziamo il grado di maturità della Sua azienda in 7 dimensioni decisive per il successo o il fallimento dell’IA.',
    dim1: 'Ha definito con chiarezza per che cosa vuole usare l’IA e perché?',
    dim2: 'I Suoi dati sono utilizzabili, strutturati e affidabili?',
    dim3: 'I Suoi processi sono abbastanza digitali per l’IA — o pieni di interruzioni manuali?',
    dim4: 'Chi ha la responsabilità? Chi porta avanti l’IA?',
    dim5: 'Il Suo team comprende l’IA ed è in grado di lavorarci?',
    dim6: 'L’innovazione è possibile o prevale il timore del rischio?',
    dim7: 'Ha sotto controllo regole, sicurezza e conformità?',
    resultLead:
      'Il risultato Le mostra a colpo d’occhio il Suo profilo IA completo, i Suoi punti di forza e i principali ambiti d’intervento.',
    startNow: 'Avvia ora il Readiness Check',
    contactTitle: 'Contatto',
    contactLead: 'Costruiamo insieme il futuro',
    email: 'E-mail',
    phone: 'Telefono',
    address: 'Indirizzo',
    formName: 'Nome',
    formEmail: 'E-mail',
    formSubject: 'Oggetto',
    formMessage: 'Messaggio',
    formSend: 'Invia il messaggio',
    formSending: 'Invio in corso…',
    formThanks: 'Grazie per il Suo messaggio. La contatteremo a breve.',
    formError:
      'Si è verificato un errore. Riprovi più tardi oppure ci contatti direttamente via e-mail.',
  },
  germanOnly: {
    check: 'Il Readiness Check è disponibile solo in tedesco.',
    transformation: 'Il Transformation Check è disponibile solo in tedesco.',
  },
  award: {
    title: 'HSLU Best AI@RE Use Case Award 2026',
    whoCanEnter: 'Chi può partecipare?',
    solutionsFrom: 'Soluzioni di IA da tutti i comparti del settore immobiliare:',
    fieldValuation: 'Valutazione & market intelligence',
    fieldConstruction: 'Costruzione & progettazione',
    fieldOperations: 'Esercizio & energia',
    fieldEsg: 'ESG & portafoglio',
    fieldFinance: 'Finanziamento & transazioni',
    fieldAgents: 'Agenti IA & automazione',
    prerequisiteLine:
      'Requisiti: un business case reale · idealmente primi clienti o progetti pilota · start-up o progetto di un’azienda affermata',
    requirementsTitle: 'Quali sono i requisiti di partecipazione?',
    req1: 'Un caso d’uso concreto di IA nell’edilizia o nel settore immobiliare',
    req2: 'Un prototipo funzionante o un prodotto finito',
    req3: 'Una start-up oppure un progetto di un’azienda affermata',
    processTitle: 'Come si svolge?',
    step1: 'Candidature entro il 30.4.2026, con un breve video, tramite il modulo qui sotto',
    step2: 'Una giuria nomina 5 candidati fra tutte le candidature entro il 10.5.2026',
    step3: 'Pitch dal vivo alla conferenza del 1.6.2026 presso l’IFZ di Rotkreuz',
    step4: 'Votazione del pubblico alla conferenza',
    step5: 'Premiazione alla conferenza del 1.6.2026',
    moreDetails: 'Ulteriori dettagli',
    apply: 'Candidati per l’award',
    backHome: 'Torna alla pagina iniziale',

    voteTitle: 'AI@RE Award 2026 · votazione del pubblico',
    voteLead:
      'Voti uno dei candidati qui sotto. Dopo aver inserito il Suo indirizzo e-mail riceverà una conferma.',
    registerConference: 'Iscriviti alla conferenza',
    loading: 'Caricamento …',
    juryVerdict: 'Il giudizio della giuria',
    close: 'Chiudi',
    castVote: 'Esprimi il voto',
    email: 'E-mail',
    emailUseNote: 'La Sua e-mail viene usata solo in relazione all’AI@RE Award 2026.',
    newsletterOptIn: 'Desidero ricevere aggiornamenti su AI@RE.',
    cancel: 'Annulla',
    confirmVote: 'Conferma il voto',
    sending: 'Invio in corso…',
    thanks: 'Grazie',
    votingClosed: 'Votazione chiusa',
    openYoutube: 'Apri su YouTube',
    openLoom: 'Apri su Loom',
    loadCandidatesError: 'Non è stato possibile caricare i candidati.',
    needEmail: 'Inserisca un indirizzo e-mail.',
    voteSaveError: 'Non è stato possibile registrare il voto.',
    genericError: 'Si è verificato un errore.',

    resultsTitle: 'AI@RE Award · voti',
    refreshing: 'Aggiornamento …',
    countsUnavailable: 'Conteggi temporaneamente non disponibili — le barre mostrano 0.',
    votingLabel: 'Votazione:',
    winnerReveal: 'And the winner is …',
    startReveal: 'And the winner is, avvia l’animazione',
    toOverview: 'Alla panoramica dell’award',
    refreshFailed: 'Aggiornamento non riuscito.',
    loadError: 'Errore di caricamento',
    restartVoting: 'Riavvia la votazione',
    stopVoting: 'Ferma la votazione',
    disableDoubleCount: 'Disattiva il conteggio doppio',
    enableDoubleCount: 'Attiva il conteggio doppio',
  },
  statistics: {
    loading: 'Caricamento delle statistiche…',
    retry: 'Riprova',
    noData: 'Nessun dato disponibile',
    loadError: 'Non è stato possibile caricare le statistiche',
    title: 'Il settore immobiliare è pronto per l’IA?',
    lead: 'Ecco lo stato attuale del nostro sondaggio.',
    companySize: 'Dimensione aziendale:',
    country: 'Paese:',
    business: 'Settore:',
    total: 'Totale:',
    submissions: 'risposte',
    all: 'Tutti',
    demoData: 'Dati dimostrativi (backend non raggiungibile). I filtri non hanno effetto.',
    overallScore: 'Valutazione complessiva',
    byDimension: 'Distribuzione per dimensione',
    average: 'Media',
    sizeOver1000: 'Più di 1000 collaboratori',
    sizeRange: (von: string): string => `${von} collaboratori`,
    chartTotal: 'Totale',
    bizAssetManagement: 'Asset management',
    bizFacilityManagement: 'Facility management',
    bizBroker: 'Intermediazione',
    bizDevelopment: 'Sviluppo immobiliare',
    bizAdministration: 'Amministrazione immobiliare',
    bizConsulting: 'Consulenza immobiliare',
    bizProjectDevelopment: 'Sviluppo di progetti',
    bizFinance: 'Finanziamento immobiliare',
    bizOther: 'Altro',
    countryDE: 'Germania',
    countryAT: 'Austria',
    countryCH: 'Svizzera',
    score1: 'Punteggio 1 – Per nulla d’accordo',
    score2: 'Punteggio 2 – Poco d’accordo',
    score3: 'Punteggio 3 – Neutrale',
    score4: 'Punteggio 4 – Abbastanza d’accordo',
    score5: 'Punteggio 5 – Pienamente d’accordo',
  },
  marketTest: {
    title: 'Dati di mercato (sintetici)',
    subtitle: 'Interfaccia di prova per il',
    query: 'Interroga',
    examples: 'Esempi:',
    inputSchema: 'Ingresso (inputSchema)',
    outputSchema: 'Uscita (outputSchema)',
    sectionLocation: 'Ubicazione e parametri',
    address: 'Indirizzo',
    addressPlaceholder: 'p. es. Bahnhofstrasse 1, 8001 Zürich',
    lat: 'Latitudine (lat)',
    lon: 'Longitudine (lon)',
    objectType: 'Tipo di immobile',
    dealType: 'Operazione (offerte)',
    minRooms: 'Locali min.',
    maxPrice: 'Prezzo max. CHF',
    listingCount: 'Numero di offerte',
    trendMetric: 'Metrica di tendenza',
    trendMonths: 'Mesi di tendenza',
    rentAvg: 'Affitto ⌀ (CHF/m²/mese)',
    priceAvg: 'Prezzo d’acquisto ⌀ (CHF/m²)',
    grossYield: 'Rendimento lordo %',
    vacancy: 'Sfitto %',
    yoy: 'YoY %',
    marketingDays: 'Tempo di commercializzazione (giorni)',
    sample: 'Campione',
    confidence: 'Affidabilità',
    start: 'Inizio',
    end: 'Fine',
    cagr: 'CAGR %',
    needAddressOrCoords:
      'Indichi un indirizzo (≥3 caratteri) OPPURE latitudine e longitudine.',
    matchCoordinates: 'Coordinate',
    matchCity: 'Nome della città',
    matchHash: 'Hash (non affidabile)',
    colDeal: 'Operazione',
    colRooms: 'Locali',
    colArea: 'Superficie m²',
    colPrice: 'Prezzo / affitto',
    colDistance: 'Distanza m',
    colListed: 'In annuncio (giorni)',
    typeApartment: 'Appartamento',
    typeCommercial: 'Commerciale',
    dealPurchase: 'Prezzo d’acquisto',
    colDescription: 'Descrizione',
    colDefault: 'Default',
  },
}
