// German UI labels. Centralized so they can be swapped later.
export const labels = {
  appTitle: 'Training',
  loading: 'Wird geladen…',
  noModules: 'Keine Module verfügbar.',
  moduleSelectLabel: 'Modul wählen',
  resetProgress: 'Fortschritt zurücksetzen',
  resetConfirm: 'Fortschritt wirklich zurücksetzen? Antworten und Notizen gehen verloren.',
  progressOf: (done: number, total: number) => `${done} / ${total} Abschnitte`,
  objectives: 'Lernziele',
  prev: 'Zurück',
  next: 'Weiter',
  submit: 'Antwort prüfen',
  tryAgain: 'Erneut versuchen',
  correct: 'Richtig',
  incorrect: 'Falsch',
  savedHint: 'gespeichert',
  validationError: 'Modul-JSON ist ungültig.',
  loadError: 'Modul konnte nicht geladen werden.',
  missingResource: (id: string) => `Ressource fehlt: ${id}`,
  missingAlt: 'Alternativtext fehlt',

  // Course/module catalog (the offering)
  catalog: {
    heading: 'Kurse & Module',
    intro: 'Wähle einen Kurs und ein Modul, um zu starten.',
    empty: 'Zurzeit sind keine Kurse verfügbar.',
    loadError: 'Kurse konnten nicht geladen werden.',
    inProgress: 'In Bearbeitung',
    open: 'Öffnen',
    backToCatalog: '← Alle Kurse',
    onlyPublished: 'Nur Veröffentlichte',
    unpublishedTag: 'Unveröffentlicht',
  },

  // Teilnehmeransicht (admin views a learner's progress/work)
  viewAs: {
    open: 'Teilnehmeransicht',
    title: 'Teilnehmeransicht',
    subtitle: 'Fortschritt einer teilnehmenden Person ansehen.',
    ownView: 'Meine Ansicht',
    noParticipants: 'Noch keine Teilnehmenden mit Fortschritt in diesem Kurs.',
    banner: (name: string) => `Teilnehmeransicht: ${name}`,
    readOnly: 'schreibgeschützt',
    exit: 'Zurück zu meiner Ansicht',
    loadError: 'Teilnehmende konnten nicht geladen werden.',
    close: 'Schliessen',
  },

  // Inline course/module editing in the catalog's Bearbeiten mode
  catalogEdit: {
    addCourse: 'Kurs hinzufügen',
    published: 'Veröffentlicht',
    publishedHint: 'Nur die aktive, veröffentlichte Version erscheint für Teilnehmende.',
    version: (n: number) => `Version ${n}`,
    activeTag: 'aktiv',
    draftTag: 'Entwurf',
    setActive: 'Als aktive Version',
    isActive: 'Aktive Version',
    clone: 'Version klonen',
    cloning: 'Wird geklont …',
    deleteVersion: 'Version löschen',
    deleteVersionConfirm: (title: string, v: number) => `Version ${v} von „${title}" wirklich löschen?`,
    deleteCourse: 'Kurs löschen',
    deleteCourseConfirm: (title: string) => `Kurs „${title}" wirklich löschen?`,
    courseTitlePlaceholder: 'Kurstitel',
    courseDescPlaceholder: 'Kurzbeschreibung des Kurses …',
    addModule: 'Modul hinzufügen',
    removeModule: 'Modul aus Kurs entfernen',
    moduleTitlePlaceholder: 'Modultitel',
    moduleDescPlaceholder: 'Kurzbeschreibung des Moduls …',
    dragToReorder: 'Zum Umordnen ziehen',
    newCourseTitle: 'Neuer Kurs',
    newModuleTitle: 'Neues Modul',
    noModules: 'Noch keine Module in diesem Kurs.',
    loadError: 'Kurse konnten nicht geladen werden.',
    saveError: 'Änderung konnte nicht gespeichert werden.',
  },

  // Learner progress dashboard (top of the catalog)
  dashboard: {
    completedCourses: 'Abgeschlossene Kurse',
    ofCourses: (done: number, total: number) => `${done} von ${total} Kursen`,
    certificates: 'Zertifikate',
    inProgressHeading: 'In Bearbeitung',
    completedTag: 'Abgeschlossen',
    noStarted: 'Noch keine Kurse begonnen — wähle unten einen Kurs, um zu starten.',
  },

  // Seat / order gate (shown when the first interaction cannot claim a seat)
  seat: {
    title: 'Kein Zugang zu diesem Kurs',
    noOrder: 'Für diesen Kurs liegt keine Bestellung Ihrer Organisation vor. Bitte wenden Sie sich an Ihre Administration.',
    noSeats: 'Für diesen Kurs sind alle Plätze belegt. Bitte wenden Sie sich an Ihre Administration.',
    generic: 'Ihr Fortschritt konnte nicht gespeichert werden.',
    close: 'Schliessen',
  },

  // LLM prompt block
  llm: {
    title: 'Prompt ausprobieren',
    model: 'Modell',
    unavailable: 'nicht verfügbar',
    promptLabel: 'Prompt',
    promptPlaceholder: 'Schreibe hier deinen Prompt …',
    send: 'Senden',
    sending: 'Wird gesendet …',
    response: 'Antwort',
    refused: 'Das Modell hat die Anfrage abgelehnt.',
    modelsError: 'Modelle konnten nicht geladen werden.',
    tokens: (input: number, output: number) => `${input} → ${output} Tokens`,
  },

  // Auth / login gate
  auth: {
    heading: 'Anmeldung Trainingsbereich',
    intro: 'Der Trainingsbereich ist geschützt. Bitte melden Sie sich mit Ihrer E-Mail-Adresse an.',
    emailLabel: 'E-Mail-Adresse',
    emailPlaceholder: 'vorname.nachname@hslu.ch',
    requestCode: 'Code anfordern',
    sending: 'Code wird gesendet…',
    codeHeading: 'Code eingeben',
    codeSentTo: (email: string) => `Wir haben einen 6-stelligen Code an ${email} gesendet. Er ist 10 Minuten gültig.`,
    codeLabel: 'Anmeldecode',
    codePlaceholder: '123456',
    verify: 'Anmelden',
    verifying: 'Wird geprüft…',
    back: 'Andere E-Mail-Adresse',
    resend: 'Code erneut senden',
    checking: 'Anmeldung wird geprüft…',
    logout: 'Abmelden',
    genericRequestError: 'Code konnte nicht gesendet werden. Bitte versuchen Sie es erneut.',
    wrongCode: 'Falscher Code. Bitte erneut versuchen.',
    wrongCodeRemaining: (n: number) => `Falscher Code. Noch ${n} Versuch(e).`,
    expiredCode: 'Der Code ist ungültig oder abgelaufen. Bitte fordern Sie einen neuen an.',
    lockedCode: 'Zu viele Versuche. Bitte fordern Sie einen neuen Code an.',
    noUser: 'Für diese Adresse besteht kein Zugang.',
    invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
  },

  // Admin panel
  admin: {
    title: 'Administration',
    noAccess: 'Kein Zugriff — dieser Bereich ist Administratoren vorbehalten.',
    tabUsers: 'Nutzer',
    showDeactivated: 'Deaktivierte anzeigen',
    createUser: 'Nutzer erstellen',
    colName: 'Name',
    colEmail: 'E-Mail',
    colRoles: 'Rollen',
    colStatus: 'Status',
    colActions: 'Aktionen',
    statusActive: 'Aktiv',
    statusDeactivated: 'Deaktiviert',
    deactivate: 'Deaktivieren',
    reactivate: 'Reaktivieren',
    noUsers: 'Keine Nutzer vorhanden.',
    loadError: 'Nutzer konnten nicht geladen werden.',
    // Create dialog
    dialogTitle: 'Neuen Nutzer erstellen',
    fFirstName: 'Vorname',
    fLastName: 'Nachname',
    fEmail: 'E-Mail-Adresse',
    fRoles: 'Rollen',
    roleAdministrator: 'Administrator',
    roleMember: 'Member',
    create: 'Erstellen',
    creating: 'Wird erstellt …',
    cancel: 'Abbrechen',
    invalidEmail: 'Bitte eine gültige E-Mail-Adresse eingeben.',
    nameRequired: 'Vor- und Nachname sind erforderlich.',
    duplicate: 'Diese E-Mail-Adresse existiert bereits.',
    // Customer
    colCustomer: 'Kunde',
    fCustomer: 'Kunde',
    newCustomerOption: 'Neuer Kunde',
    fCustomerName: 'Kundenname',
    fStreet: 'Strasse',
    fStreetNumber: 'Nr.',
    fPostalCode: 'PLZ',
    fCity: 'Ort',
    fCountry: 'Land',
    customerRequired: 'Bitte einen Kunden wählen oder anlegen.',
    customerNameRequired: 'Kundenname ist erforderlich.',
    addressRequired: 'Alle Adressfelder sind erforderlich.',
  },

  // MCP toolset inspector block
  mcp: {
    url: 'MCP-Server-URL',
    urlPlaceholder: 'https://…/mcp',
    connect: 'Verbinden',
    connecting: 'Verbinde …',
    connected: 'Verbunden',
    disconnect: 'Trennen',
    tools: 'Tools',
    noTools: 'Der Server meldet keine Tools.',
    selectToolHint: 'Wähle links ein Tool, um es auszuführen.',
    parameters: 'Parameter',
    noParams: 'Dieses Tool hat keine Parameter.',
    run: 'Ausführen',
    running: 'Wird ausgeführt …',
    result: 'Ergebnis',
    error: 'Fehler',
    required: 'erforderlich',
    stepUrl: 'Server verbunden',
    stepTool: 'Tool ausgeführt',
    done: 'Abgeschlossen',
  },

  // Ontology explorer block (data-room metamodel)
  ontologyBlock: {
    classes: 'Klassen',
    relationships: 'Beziehungen',
    node: 'Knoten',
    edge: 'Kante',
    erpCore: 'ERP-Kern',
    extensions: 'Erweiterungen',
    erpTag: 'ERP',
    extensionTag: 'geplant',
    attributes: 'Attribute',
    relOut: 'Beziehungen (ausgehend)',
    relIn: 'Beziehungen (eingehend)',
  },

  // Data-room SQL explorer block
  dataQuery: {
    run: 'Ausführen',
    running: 'Läuft …',
    hint: '⌘/Ctrl + Enter',
    syntaxToggle: 'Unterstützte Syntax',
    syntaxBody:
      'Eine Tabelle (Klasse aus der Ontologie), keine JOINs. WHERE mit AND/OR und = != < <= > >= LIKE. Nur Lesezugriff.',
    rowCount: (n: number, coll: string) => `${n} Zeile${n === 1 ? '' : 'n'} aus ${coll}`,
    noRows: 'Keine Zeilen — passe die Bedingungen an.',
  },

  // Document → Markdown converter block
  docConvert: {
    drop: 'Datei hierher ziehen oder klicken',
    formats: 'PDF, PPTX, DOCX, Bilder → Markdown · Excel → Markdown + Serialisierung + Analyse',
    converting: 'Konvertiere …',
    raw: 'Rohtext',
    rendered: 'Gerendert',
    copyAll: 'Alles kopieren',
    copied: 'Kopiert ✓',
    tab: { markdown: 'Markdown', serialized: 'Serialisiert', analysis: 'Analyse' },
  },

  // Data-room object-graph explorer block
  objectGraph: {
    seed: 'Start:',
    hint: 'Klicke einen Knoten, um Nachbarn zu laden',
    nodeCount: (n: number) => `${n} Knoten`,
    cypherRun: 'Abfragen',
    cypherClear: 'Zurücksetzen',
    cypherPlaceholder: "MATCH (a:Liegenschaft)<-[:liegt_in]-(u:Einheit) RETURN a, u",
    matchCount: (n: number) => `${n} Treffer hervorgehoben`,
  },

  // Course-material chat assistant
  chat: {
    title: 'Kurs-Assistent',
    subtitle: 'Fragen zu den Kursunterlagen',
    open: 'Assistent öffnen',
    close: 'Schliessen',
    welcome: 'Hallo! Ich beantworte Fragen zu den AI@RE-Kursunterlagen. Was möchten Sie wissen?',
    suggestionsTitle: 'Beliebte Fragen',
    suggestions: [
      'Was ist AI Readiness?',
      'Erkläre den Transformation Circle',
      'Wie hilft KI bei der Bewertung?',
    ],
    placeholder: 'Frage eingeben …',
    send: 'Senden',
    sources: 'Quellen',
    disclaimer: 'Antworten können Fehler enthalten. Bitte prüfen Sie wichtige Informationen.',
    error: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
  },

  // Admin: Bestellungen tab + order dialog
  adminOrders: {
    tab: 'Bestellungen',
    heading: 'Bestellungen',
    colCourse: 'Kurs',
    colCustomer: 'Kunde',
    colPeriod: 'Zeitraum',
    colSeats: 'Plätze',
    noOrders: 'Noch keine Bestellungen vorhanden.',
    loadError: 'Bestellungen konnten nicht geladen werden.',
    // Order action + dialog
    order: 'Bestellen',
    newOrder: 'Neue Bestellung',
    dialogTitle: (course: string) => `Bestellung: ${course}`,
    fCourse: 'Kurs',
    noCoursesForOrder: 'Bitte zuerst einen Kurs anlegen.',
    fCustomer: 'Kunde',
    fSeats: 'Anzahl Plätze',
    fStart: 'Startdatum',
    fEnd: 'Enddatum',
    noCustomers: 'Bitte zuerst einen Kunden anlegen.',
    create: 'Bestellen',
    creating: 'Wird erstellt …',
    cancel: 'Abbrechen',
  },

  // Admin: Kursdurchführung tab
  adminInstances: {
    tab: 'Kursdurchführung',
    heading: 'Kursdurchführungen',
    colCourse: 'Kurs',
    colTrainers: 'Trainer',
    colParticipants: 'Teilnehmer',
    colStart: 'Startdatum',
    noInstances: 'Noch keine Durchführungen vorhanden.',
    loadError: 'Durchführungen konnten nicht geladen werden.',
    count: (n: number) => `${n} ${n === 1 ? 'Person' : 'Personen'}`,
    // action + dialog
    add: 'Durchführung anlegen',
    newInstance: 'Neue Durchführung',
    editInstance: 'Durchführung bearbeiten',
    edit: 'Bearbeiten',
    save: 'Speichern',
    saving: 'Wird gespeichert …',
    colActions: 'Aktionen',
    fCourse: 'Kurs',
    fParticipants: 'Teilnehmer',
    fTrainers: 'Trainer',
    fStart: 'Startdatum',
    version: (n: number) => `Version ${n}`,
    noCourses: 'Bitte zuerst einen Kurs anlegen.',
    searchPlaceholder: 'Nach Name oder E-Mail filtern …',
    noneSelected: 'Niemand ausgewählt',
    noMatches: 'Keine Treffer',
    create: 'Anlegen',
    creating: 'Wird angelegt …',
    cancel: 'Abbrechen',
  },

  // Admin: Claude Skill tab
  adminSkill: {
    tab: 'Claude Skill',
    download: 'Skill herunterladen (.zip)',
    copied: 'Kopiert',
    copy: 'Kopieren',
  },

  // Admin: Kunden tab
  adminCustomers: {
    tab: 'Kunden',
    heading: 'Kunden',
    createCustomer: 'Kunde erstellen',
    createCustomerTitle: 'Neuen Kunden erstellen',
    editCustomerTitle: 'Kunde bearbeiten',
    edit: 'Bearbeiten',
    save: 'Speichern',
    saving: 'Wird gespeichert …',
    colName: 'Kunde',
    colAddress: 'Adresse',
    colUsers: 'Nutzer',
    colActions: 'Aktionen',
    noUsers: '—',
    noCustomers: 'Noch keine Kunden vorhanden.',
    loadError: 'Kunden konnten nicht geladen werden.',
  },

  // Edit mode (Administrator)
  editor: {
    enterEditMode: 'Bearbeiten',
    exitEditMode: 'Fertig',
    save: 'Speichern',
    saving: 'Wird gespeichert …',
    saved: 'Gespeichert',
    saveError: 'Speichern fehlgeschlagen',
    edit: 'Block bearbeiten',
    delete: 'Block löschen',
    dragToReorder: 'Zum Umordnen ziehen',
    paletteTitle: 'Blöcke',
    paletteHint: 'Auf die Trainingsfläche ziehen oder klicken zum Anhängen.',
    dialogTitle: (typeLabel: string) => `${typeLabel} bearbeiten`,
    cancel: 'Abbrechen',
    addItem: 'Hinzufügen',
    removeItem: 'Entfernen',
    markCorrect: 'Richtig',
    // Field labels
    fBody: 'Text',
    fTitle: 'Titel (optional)',
    fItems: 'Punkte',
    fVariant: 'Variante',
    fStem: 'Frage',
    fOptions: 'Optionen',
    fOptionText: 'Antworttext',
    fFeedback: 'Feedback',
    fExplanation: 'Erläuterung (optional)',
    fScenario: 'Szenario',
    fOptionLabel: 'Bezeichnung',
    fPrompt: 'Aufgabenstellung',
    fGuidance: 'Hinweis (optional)',
    fResource: 'Ressource',
    fResourceOptional: '… oder Ressource aus der Bibliothek',
    fMediaUrl: 'Medien-URL',
    mediaUrlPlaceholder: 'https://… (Bild, Video oder YouTube/Vimeo)',
    mediaDetected: 'Erkannt',
    mediaUrlWins: 'Die URL wird verwendet, solange sie gesetzt ist.',
    mediaEmpty: 'Kein Medium – im Editor eine URL hinzufügen.',
    // BPMN modeling block
    bpmnSave: 'Diagramm speichern',
    bpmnSaving: 'Wird gespeichert …',
    bpmnSaved: 'Gespeichert',
    bpmnError: 'Der Modeler konnte nicht geladen werden.',
    bpmnExpand: 'Vollbild',
    bpmnCollapse: 'Vollbild verlassen',
    bpmnEditorHint: 'Das Diagramm zeichnen die Teilnehmenden selbst; es wird in ihrem Fortschritt gespeichert.',
    fMcpDefaultUrl: 'Vorbelegte MCP-URL (optional)',
    mcpEditorHint: 'Teilnehmende geben eine MCP-URL ein und führen ein Tool aus; der Block gilt als erledigt, sobald beides passiert ist.',
    ontologyEditorHint: 'Das Metamodell kommt live aus dem Datenraum; der Block gilt als erledigt, sobald eine Klasse geöffnet wurde.',
    fDefaultQuery: 'Vorbelegte SQL-Abfrage (optional)',
    dataQueryEditorHint: 'Teilnehmende schreiben eine SELECT-Abfrage gegen den Datenraum; der Block gilt als erledigt, sobald eine Abfrage lief.',
    fStartType: 'Start-Klasse (z. B. Site)',
    objectGraphEditorHint: 'Der Graph kommt live aus dem Datenraum; der Block gilt als erledigt, sobald ein Knoten expandiert wurde.',
    docConvertEditorHint: 'Teilnehmende laden eine Datei hoch; der Block gilt als erledigt, sobald eine Konvertierung lief. Der Dokumentendienst muss serverseitig konfiguriert sein.',
    fCaption: 'Bildunterschrift (optional)',
    noResources: 'Keine Ressourcen in diesem Modul definiert.',
    variantNote: 'Hinweis',
    variantInsight: 'Erkenntnis',
    variantWarning: 'Warnung',
    variantExample: 'Beispiel',
    fInstructions: 'Einleitung (optional)',
    fDefaultPrompt: 'Vorbelegter Prompt (optional)',
    fDefaultModel: 'Standardmodell',
    fDefaultModelAuto: 'Automatisch',
    fAllowModelChoice: 'Modellwahl erlauben',
    fAllowParamEditing: 'Parameter bearbeitbar (z. B. Temperature)',
    // Sections
    addSection: 'Abschnitt',
    removeSection: 'Abschnitt entfernen',
    removeSectionConfirm: (title: string) => `Abschnitt „${title}" mit allen Blöcken entfernen?`,
    sectionTitlePlaceholder: 'Abschnittstitel',
    // Markdown editor
    mdEdit: 'Bearbeiten',
    mdPreview: 'Vorschau',
    mdEmpty: 'Nichts zu zeigen.',
    mdH1: 'Überschrift 1',
    mdH2: 'Überschrift 2',
    mdH3: 'Überschrift 3',
    mdBold: 'Fett',
    mdItalic: 'Kursiv',
    mdUl: 'Aufzählung',
    mdOl: 'Nummerierte Liste',
    mdQuote: 'Zitat',
    mdLink: 'Link',
    mdCode: 'Code',
    mdMedia: 'Medien einfügen',
    mdUpload: 'Datei hochladen',
    mdDropHint: 'Dateien hier ablegen zum Hochladen',
    mdUploading: 'Lädt hoch …',
  },

  // Kodieroberfläche der Enforcement-Signal-Studie (/enforcement-signal)
  enforcement: {
    title: 'Kodierung Enforcement-Signal',
    noOpenStudy: 'Zurzeit läuft keine Erhebung.',
    loading: 'Wird geladen …',
    loadError: 'Die Sitzung konnte nicht geladen werden.',
    retry: 'Erneut versuchen',

    // Lesemodus: ohne Rolle (auch nicht angemeldet) sichtbar, aber nicht beschreibbar
    readOnly: {
      heading: 'Lesemodus',
      body:
        'Diese Seite ist öffentlich einsehbar. Kodiert wird nur auf Einladung: dafür braucht es ein Benutzerkonto mit der Rolle für diese Studie. Sie sehen hier das vollständige Kodierprotokoll und ein Beispiel-Item mit allen Eingabefeldern — Eingaben sind jedoch nicht möglich und es wird nichts gespeichert.',
      loginHint: 'Sie sind zur Studie eingeladen?',
      login: 'Anmelden',
      showExample: 'Beispiel-Item ansehen',
      exampleHeading: 'Beispiel-Item',
      exampleLead: (total: number) =>
        `Eines von ${total} Items der Erhebung. Kodierende erhalten die Items einzeln und in einer für sie zufälligen Reihenfolge; welche Vorschriften die Stichprobe enthält, wird hier nicht gezeigt.`,
      backToProtocol: 'Zurück zum Protokoll',
      exampleError: 'Das Beispiel-Item konnte nicht geladen werden.',
    },

    // Startseite
    introHeading: 'Kodierprotokoll',
    introLead:
      'Bitte lesen Sie das Protokoll vollständig, bevor Sie beginnen. Es bleibt während der Kodierung jederzeit aufklappbar.',
    acknowledge: 'Ich habe das Protokoll gelesen',

    // Protokoll-Panel während der Kodierung
    protocolPanel: 'Kodierprotokoll',

    // Item-Ansicht
    position: (n: number, total: number) => `Item ${n} von ${total}`,
    undecidable: 'nicht entscheidbar',
    optional: '(optional)',
    yes: 'Ja',
    no: 'Nein',
    excerptTruncated: 'Der Auszug ist gekürzt.',
    rangeHint: (min: number, max: number) => `${min}–${max}`,
    rangeMinHint: (min: number) => `ab ${min}`,
    rangeMaxHint: (max: number) => `bis ${max}`,
    lookedUp: 'Ich habe über den gezeigten Text hinaus nachgeschlagen',
    lookedUpHint: 'Nachschlagen ist erlaubt und erwünscht — es wird lediglich gezählt.',
    commentLabel: 'Bemerkung (optional)',
    commentPlaceholder: 'z. B. worin die Unklarheit besteht',
    next: 'Weiter',
    saving: 'Wird gespeichert …',
    saveError: 'Die Antwort konnte nicht gespeichert werden. Bitte erneut versuchen.',
    itemError: 'Das Item konnte nicht geladen werden.',
    numberInvalid: 'Bitte eine ganze Zahl eingeben.',
    numberMin: (min: number) => `Der Wert muss mindestens ${min} betragen.`,
    numberMax: (max: number) => `Der Wert darf höchstens ${max} betragen.`,

    // Korrekturfunktion
    correctionsOpen: 'Frühere Antwort korrigieren',
    correctionsHeading: 'Bereits kodierte Items',
    correctionsIntro:
      'Eine Korrektur ersetzt die ursprüngliche Antwort nicht, sondern wird als neue Fassung gespeichert.',
    correctionsLocalNote:
      'Diese Liste wird in diesem Browser geführt. An einem anderen Gerät erscheint sie leer — die Kodierungen selbst liegen unverändert auf dem Server.',
    correctionsEmpty: 'Noch nichts kodiert.',
    correctionOf: (n: number) => `Korrektur zu Item ${n}`,
    saveCorrection: 'Korrektur speichern',
    back: 'Zurück zur Kodierung',
    ratedAt: (d: string) => `kodiert am ${d}`,

    // Alle Items kodiert, noch nicht abgeschlossen
    finishHeading: 'Alle Items kodiert',
    finishCount: (n: number) => (n === 1 ? 'Sie haben 1 Item kodiert.' : `Sie haben ${n} Items kodiert.`),
    finishHint:
      'Mit dem Abschluss wird die Kodierung gesperrt. Danach sind keine Eingaben und keine Korrekturen mehr möglich.',
    finish: 'Kodierung abschliessen',
    finishConfirm: 'Endgültig abschliessen',
    finishCancel: 'Abbrechen',
    finishing: 'Wird abgeschlossen …',
    finishError: 'Der Abschluss konnte nicht gespeichert werden. Bitte erneut versuchen.',

    // Abschlussseite
    doneHeading: 'Kodierung abgeschlossen',
    doneCount: (n: number) =>
      n === 1 ? '1 Item wurde kodiert und übermittelt.' : `${n} Items wurden kodiert und übermittelt.`,
    doneLocked: 'Weitere Eingaben sind nicht mehr möglich.',
    doneThanks: 'Vielen Dank für Ihre Mitarbeit.',
  },
} as const
